version: 2.1

orbs:
  config-splitting: circle-makotom-orbs/config-splitting@0.0.8

setup: false


jobs:
  build-shared:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello from my shared job"
    
  echo-output:
    docker:
      image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: generate output
          command: |
            chmod +x .circleci/generate-output.sh && ./generate-output.sh




workflows:
  main-workflow:
    jobs:
      - build-shared # this job will always run
      - echo-output
      # - config-splitting/run-modular-configs-selectively:
      #     module-list-file: .circleci/list-of-dirs-to-monitor.txt
      #     base-revision: main
      #     requires:
      #       - build-shared

# VS Code Extension Version: 1.1.1